spring:
  datasource:
    dynamic:
      primary: self_db
      datasource:
        self_db:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/self_db?allowMultiQueries=true #批量更新需要设置?allowMultiQueries=true，否则报错
          username: root
          password: qlk123456
        sakila:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/sakila
          username: root
          password: qlk123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 7071